### PR TITLE
feat: migrating the wcme track to webrtc core

### PR DESCRIPTION
**Pull request by arun3528**
Moved the track related logic from https://sqbu-github.cisco.com/CPaaS/web-client-media-engine/tree/main/src
to webrtc core 

Removed the effects for now untill we export public types for the effects 

Did some minor test fixes , no other changes are done for now 

moved some of the eslint rules from wcme to core

### CODE REVIEW

**Comment by bbaldino** [comment]
Did you have to make any changes to the files being copied over? Or is it all copy-paste from wcme?

**Comment by arun3528** [comment]
@bbaldino  yep only the files in the wcme branch thats it

**Review by bbaldino — APPROVED** [review]
This is hard to review without being able to see what (if anything) has changed from the other repo, but if you're saying the files and specs are all just copy-pasted, then lgtm.  If you could add some comments to anything that has changed, that'd be helpful.

**Comment by arun3528** [comment]
sure @bbaldino  did not touch any of the track related stuff , eslint , test fix and logger (moved from WCME)

once i raise a PR for WCME next you should see what has been removed and what the function names 

will have a PR ready by tomorrow for WCME 

I have no plans to change any track without having a proposal for it or JIRA (Might take help from WCME team )

**Pull request merged**
