### PR TITLE
feat(bnr): add getEffects and modify disposeEffects

### PR DESCRIPTION
**Pull request by lismith2-cisco**
Need a better interface for applying effects for implementing bnr in webex web client

### CODE REVIEW

**Review by bbaldino — APPROVED** [review]

**Comment by bbaldino** [comment]
Out of curiosity, what's the use case to get a map of all the effects?

**Comment by lismith2-cisco** [comment]
> Out of curiosity, what's the use case to get a map of all the effects?

 When selecting 'no optimization' I want to disable any current effect (but not dispose it) so it can be re-enabled quickly. There were a couple of options for how to do it, but this seemed best.

**Comment by bbaldino** [comment]
> When selecting 'no optimization' I want to disable any current effect (but not dispose it) so it can be re-enabled quickly. There were a couple of options for how to do it, but this seemed best.

@shaofan-qi I have a vague memory of you finding some issues around disabling but not "removing" effects, am I remembering that right?  Should effects be removed completely when they're not in use?  cc @andiwils who might have some thoughts as well.

**Comment by bbaldino** [comment]
Some comments from @andiwils offline:

> If they will never be used again, they should be disposed of. With VBG, disabling still ate up a bunch of CPU until recently when we decided to just swap the original track with the effect track. We are not doing that with BNR yet but plan to.
> In other words, disabling should have similar performance to not using the effect at all. That much is true with VBG today. Quality shouldn't be affected.

So sounds like even if this might currently have some issues, it's how things _should_ work.

**Comment by shaofan-qi** [comment]
The issue we met was about BNR in Safari. Even the effect was disabled, it resulted in stuttering audio. We may need to look into what's going wrong with the BNR effect. If I remember right, the issue disppears in some newer Safari versions (16.0+) on Intel Macs, but still exists on Apple Silicon Macs, but we haven't tested that for a while.

**Pull request merged**
